import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Actor } from "next/font/google";
// 1. REMOVE localFont import
// import localFont from "next/font/local"; 
import "./globals.css";
import CustomCursor from "./components/CustomCursor";

// 2. Initialize Inter for your main body text
const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter' // Assign to a variable
}); 

const actor = Actor({ 
  subsets: ["latin"],
  weight: ["400"], 
});

// 3. REMOVE the kalderaFont initialization
/*
const kalderaFont = localFont({
  src: './font/PS-Kaldera-Regular.otf',
  variable: '--font-kaldera' 
});
*/

export const metadata: Metadata = {
  title: "Praveen's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 4. REMOVE kalderaFont.variable */}
      <body className={`${actor.className}`}> 
        {children}
        <CustomCursor />
      </body>
    </html>
  );
}